INSERT INTO EMPRESA(RAZAOSOCIAL,CNPJ,EMAIL,SENHA) VALUES('StepDev', '12345678901234', 'stepdev@email.com', '12345')

INSERT INTO CADASTRO(NOME, EMAIL, SENHA) VALUES('Mateus', 'mateus@fiap.com.br', '170703')
INSERT INTO CADASTRO(NOME, EMAIL, SENHA) VALUES('Amanda', 'amanda@fiap.com.br', '12345')
INSERT INTO CADASTRO(NOME, EMAIL, SENHA) VALUES('Jean', 'jean@fiap.com.br', '54321')
INSERT INTO CADASTRO(NOME, EMAIL, SENHA) VALUES('Kaio', 'kaio@fiap.com.br', '00000')

INSERT INTO TIPO(TIPO, DATACADASTRO) VALUES('Inseto', TO_DATE('2023-06-01', 'YYYY-MM-DD'))
INSERT INTO TIPO(TIPO, DATACADASTRO) VALUES('Fungo', TO_DATE('2023-06-02', 'YYYY-MM-DD'))
INSERT INTO TIPO(TIPO, DATACADASTRO) VALUES('Lagarta', TO_DATE('2023-06-03', 'YYYY-MM-DD'))
INSERT INTO TIPO(TIPO, DATACADASTRO) VALUES('Fungo', TO_DATE('2023-06-04', 'YYYY-MM-DD'))

INSERT INTO PESTE(NOMEPOPULAR, NOMECIENTIFICO, METODODECONTROLE) VALUES('Antracnose', 'Colletotrichum truncatum', 'Fungicidas')
INSERT INTO PESTE(NOMEPOPULAR, NOMECIENTIFICO, METODODECONTROLE) VALUES('Ferrugem da soja', 'Phakopsora pachyrhizi', 'Fungicidas')
INSERT INTO PESTE(NOMEPOPULAR, NOMECIENTIFICO, METODODECONTROLE) VALUES('Lagarta-do-cartucho', 'Spodoptera frugiperda', 'Inseticidas')
INSERT INTO PESTE(NOMEPOPULAR, NOMECIENTIFICO, METODODECONTROLE) VALUES('Pulgão', 'Aphidoidea', 'Inseticidas, predadores naturais')
INSERT INTO PESTE(NOMEPOPULAR, NOMECIENTIFICO, METODODECONTROLE) VALUES('Broca-do-café', 'Hypothenemus hampei', 'Manejo integrado de pragas')



